# Generated by Django 4.0.3 on 2022-04-06 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rmmain', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user',
            new_name='username',
        ),
    ]
