# Generated by Django 4.0.3 on 2022-04-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmmain', '0003_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roomtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomtype', models.CharField(max_length=200)),
            ],
        ),
    ]
