# Generated by Django 4.0.3 on 2022-04-09 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rmmain', '0005_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=10000)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rmmain.location')),
                ('roomtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rmmain.roomtype')),
            ],
        ),
    ]
