# Generated by Django 4.0.3 on 2022-04-11 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rmmain', '0007_room_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slotdelay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slotrange', models.IntegerField(default=1)),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rmmain.manager')),
            ],
        ),
    ]
