# Generated by Django 4.0.3 on 2022-04-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmmain', '0008_slotdelay'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotdelay',
            name='bookbefore',
            field=models.IntegerField(default=1),
        ),
    ]
