# Generated by Django 4.0.3 on 2022-04-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmmain', '0010_timing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timing',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='timing',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='timing',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='timing',
            name='sunday',
        ),
        migrations.RemoveField(
            model_name='timing',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='timing',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='timing',
            name='wednesday',
        ),
        migrations.AddField(
            model_name='timing',
            name='efriday',
            field=models.TimeField(blank=True, default='21:00:00'),
        ),
        migrations.AddField(
            model_name='timing',
            name='emonday',
            field=models.TimeField(blank=True, default='21:00:00'),
        ),
        migrations.AddField(
            model_name='timing',
            name='esaturday',
            field=models.TimeField(blank=True, default='21:00:00'),
        ),
        migrations.AddField(
            model_name='timing',
            name='esunday',
            field=models.TimeField(blank=True, default='21:00:00'),
        ),
        migrations.AddField(
            model_name='timing',
            name='ethursday',
            field=models.TimeField(blank=True, default='21:00:00'),
        ),
        migrations.AddField(
            model_name='timing',
            name='etuesday',
            field=models.TimeField(blank=True, default='21:00:00'),
        ),
        migrations.AddField(
            model_name='timing',
            name='ewednesday',
            field=models.TimeField(blank=True, default='21:00:00'),
        ),
        migrations.AddField(
            model_name='timing',
            name='sfriday',
            field=models.TimeField(blank=True, default='09:00:00'),
        ),
        migrations.AddField(
            model_name='timing',
            name='smonday',
            field=models.TimeField(blank=True, default='09:00:00'),
        ),
        migrations.AddField(
            model_name='timing',
            name='ssaturday',
            field=models.TimeField(blank=True, default='09:00:00'),
        ),
        migrations.AddField(
            model_name='timing',
            name='ssunday',
            field=models.TimeField(blank=True, default='09:00:00'),
        ),
        migrations.AddField(
            model_name='timing',
            name='sthursday',
            field=models.TimeField(blank=True, default='09:00:00'),
        ),
        migrations.AddField(
            model_name='timing',
            name='stuesday',
            field=models.TimeField(blank=True, default='09:00:00'),
        ),
        migrations.AddField(
            model_name='timing',
            name='swednesday',
            field=models.TimeField(blank=True, default='09:00:00'),
        ),
    ]
