# Generated by Django 4.0.3 on 2022-04-12 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rmmain', '0012_alter_room_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='address',
            field=models.CharField(default=0, max_length=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rmmain.location'),
        ),
    ]
