# Generated by Django 4.0.3 on 2022-04-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmmain', '0013_room_address_alter_room_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='pnumber',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
