# Generated by Django 4.0.3 on 2022-04-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmmain', '0014_manager_pnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='pnumber',
            field=models.CharField(max_length=11),
        ),
    ]
