# Generated by Django 4.0.3 on 2022-04-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmmain', '0015_alter_manager_pnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='mnumber',
            field=models.CharField(default=9073383828, max_length=11),
            preserve_default=False,
        ),
    ]
