# Generated by Django 4.0.3 on 2022-04-13 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rmmain', '0017_alter_manager_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField(blank=True)),
                ('enddate', models.DateField(blank=True)),
                ('slotstart', models.TimeField(blank=True)),
                ('slotend', models.TimeField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rmmain.customer')),
                ('roomid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rmmain.room')),
            ],
        ),
    ]
