# Generated by Django 4.0.3 on 2022-04-13 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rmmain', '0018_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='manager',
            field=models.ForeignKey(default='NULL', on_delete=django.db.models.deletion.CASCADE, to='rmmain.manager'),
            preserve_default=False,
        ),
    ]
