# Generated by Django 4.0.3 on 2022-04-13 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rmmain', '0019_booking_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='manager',
        ),
    ]
