# Generated by Django 4.0.3 on 2022-04-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmmain', '0025_alter_booking_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='valid',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
