# Generated by Django 4.0.3 on 2022-04-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmmain', '0026_booking_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='slotend',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='slotstart',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
